export const AUTH_POOL = "AUTH_POOL";
export const AUTH_DATABASE = "AUTH_DATABASE";
export const SIGNING_KEY_REPOSITORY = "SIGNING_KEY_REPOSITORY";
export const USER_REPOSITORY = "USER_REPOSITORY";
export const RBAC_REPOSITORY = "RBAC_REPOSITORY";
export const INVITE_REPOSITORY = "INVITE_REPOSITORY";
export const AUTHENTICATION_REPOSITORY = "AUTHENTICATION_REPOSITORY";
export const SESSION_REPOSITORY = "SESSION_REPOSITORY";
