import type { AuditEventInput } from "../../audit/audit-event";
import type { MfaChannel } from "../mfa-challenge";
import type { AuthenticationPurpose } from "../authentication-attempt";
import type { NewRecoveryCode } from "../recovery-code";
import type { NewSessionWrite, ResolvedAccess } from "../../users/user";
import type { SignAccessToken } from "../../crypto/jwt";
import type { SecondFactor } from "../authentication-attempt";
export interface StartInviteAttemptCommand { id:string; tokenHash:string; userId:string; inviteId:string; proposedPasswordHash:string; proposedPhoneE164:string; proposedMfaChannel:MfaChannel; challenge:{id:string;providerChallengeId:string;requestedChannel:MfaChannel;reportedChannel:MfaChannel;expiresAt:Date;invalidatedAt:Date|null}; expiresAt:Date; invalidatedAt:Date|null; now:Date;auditEvents:readonly AuditEventInput[]; }
export interface PreparedOtpCheck { attemptId:string;userId:string;purpose:AuthenticationPurpose;challengeId:string;providerChallengeId:string;requestedChannel:MfaChannel;reportedChannel:MfaChannel; }
export interface InvalidateOtpChallengeCommand {attemptId:string;challengeId:string;now:Date;auditEvent:AuditEventInput}
export interface EnrollmentCommit {userId:string;sessionId:string;accessToken:string;refreshTokenExpiresAt:Date;access:ResolvedAccess}
export interface CompleteInviteEnrollmentCommand {attemptTokenHash:string;challengeId:string;recoveryCodes:readonly NewRecoveryCode[];newSession:NewSessionWrite;verifiedAt:Date;context:import("../../common/request-context").RequestContext;auditEvents:readonly AuditEventInput[]}
export interface StartLoginAttemptCommand {id:string;tokenHash:string;userId:string;secondFactor:SecondFactor;firstMethods:readonly ["pwd"];challenge:{id:string;providerChallengeId:string;requestedChannel:MfaChannel;reportedChannel:MfaChannel;expiresAt:Date;invalidatedAt:Date|null}|null;expiresAt:Date;invalidatedAt:Date|null;now:Date;auditEvents:readonly AuditEventInput[]}
export interface PreparedMfaResend {attemptId:string;userId:string;phoneE164:string;channel:MfaChannel}
export interface ReplaceMfaChallengeCommand {attemptId:string;challenge:{id:string;providerChallengeId:string;requestedChannel:MfaChannel;reportedChannel:MfaChannel;expiresAt:Date;invalidatedAt:Date|null};now:Date;auditEvents:readonly AuditEventInput[]}
export interface CompleteLoginCommand {attemptTokenHash:string;challengeId:string|null;recoveryCodeHash:string|null;newSession:NewSessionWrite;verifiedAt:Date;auditEvents:readonly AuditEventInput[]}
export interface AuthenticationRepository { startInviteAttempt(c:StartInviteAttemptCommand):Promise<"created"|"invalid_invite">; startLoginAttempt(c:StartLoginAttemptCommand):Promise<"created"|"invalid">; prepareOtpCheck(c:{attemptTokenHash:string;now:Date}):Promise<PreparedOtpCheck|"invalid">; attemptPurpose(attemptTokenHash:string,now:Date):Promise<AuthenticationPurpose|"invalid">; prepareMfaResend(attemptTokenHash:string,now:Date):Promise<PreparedMfaResend|"invalid">; replaceMfaChallenge(c:ReplaceMfaChallengeCommand):Promise<"replaced"|"invalid">; invalidateOtpChallenge(c:InvalidateOtpChallengeCommand):Promise<"invalidated"|"invalid">; recordAuditEvent(event:AuditEventInput):Promise<void>; completeInviteEnrollment(c:CompleteInviteEnrollmentCommand,sign:SignAccessToken):Promise<EnrollmentCommit|"invalid">; completeLogin(c:CompleteLoginCommand,sign:SignAccessToken):Promise<EnrollmentCommit|"invalid">; }
