import { Body, Controller, HttpCode, HttpStatus, Inject, Post, Req } from "@nestjs/common";
import { z } from "zod";
import { InspectInviteUseCase } from "../invites/usecases/inspect-invite.usecase";
import { StartInviteAcceptanceUseCase } from "../authentication/usecases/start-invite-acceptance.usecase";
import type { Request } from "express";
import { StartLoginUseCase } from "../authentication/usecases/start-login.usecase";
import { CompleteLoginUseCase } from "../authentication/usecases/complete-login.usecase";
import { ResendMfaUseCase } from "../authentication/usecases/resend-mfa.usecase";
@Controller("auth") export class PublicAuthController { constructor(@Inject(InspectInviteUseCase) private readonly inspect:InspectInviteUseCase,@Inject(StartInviteAcceptanceUseCase) private readonly start:StartInviteAcceptanceUseCase,@Inject(StartLoginUseCase) private readonly login:StartLoginUseCase,@Inject(CompleteLoginUseCase) private readonly complete:CompleteLoginUseCase,@Inject(ResendMfaUseCase) private readonly resend:ResendMfaUseCase) {} private context(request:Request){return request.context??{correlationId:"",ipAddress:null,userAgent:null};} @Post("invites/inspect") async inspectInvite(@Body() body:unknown) { const {token}=z.object({token:z.string().min(1)}).strict().parse(body); return this.inspect.execute(token); } @Post("invites/accept") async accept(@Body() body:unknown,@Req() request:Request){const value=z.object({token:z.string().min(1).max(1024),password:z.string().min(1).max(1024),phone:z.string().min(1).max(64),channel:z.enum(["sms","whatsapp"])}).strict().parse(body);return this.start.execute({inviteToken:value.token,password:value.password,phoneE164:value.phone,mfaChannel:value.channel,context:this.context(request)});} @Post("login") @HttpCode(HttpStatus.ACCEPTED) async startLogin(@Body() body:unknown,@Req() request:Request){const value=z.object({email:z.string().min(1).max(320),password:z.string().min(1).max(1024),secondFactor:z.enum(["otp","recovery"])}).strict().parse(body);return this.login.execute({...value,context:this.context(request)});} @Post("mfa/verify") async verifyMfa(@Body() body:unknown,@Req() request:Request){const value=z.object({mfaToken:z.string().min(1).max(1024),code:z.string().regex(/^\d{6}$/)}).strict().parse(body);return this.complete.verifyOtp({...value,context:this.context(request)});} @Post("mfa/recover") async recoverMfa(@Body() body:unknown,@Req() request:Request){const value=z.object({mfaToken:z.string().min(1).max(1024),recoveryCode:z.string().min(1).max(128)}).strict().parse(body);return this.complete.recover({...value,context:this.context(request)});} @Post("mfa/resend") @HttpCode(HttpStatus.ACCEPTED) async resendMfa(@Body() body:unknown){const value=z.object({mfaToken:z.string().min(1).max(1024)}).strict().parse(body);return this.resend.execute(value.mfaToken);}}
