import { RequiredDependencyUnavailableError } from "../common/errors";
import type { MfaChannel } from "./mfa-challenge";
import type { OtpVerificationGateway } from "./otp-verification.gateway";
type TwilioResponse={sid?:unknown;channel?:unknown;status?:unknown};
function channel(value:unknown):MfaChannel|null{return value==="sms"||value==="whatsapp"?value:null;}
export class TwilioVerifyGateway implements OtpVerificationGateway {
  private readonly base:string; private readonly authorization:string;
  constructor(input:{accountSid:string;authToken:string;verifyServiceSid:string;timeoutMs:number;whatsappEnabled:boolean;fetcher?:typeof fetch}) { this.base=`https://verify.twilio.com/v2/Services/${input.verifyServiceSid}`; this.authorization=`Basic ${Buffer.from(`${input.accountSid}:${input.authToken}`).toString("base64")}`; this.timeoutMs=input.timeoutMs; this.whatsappEnabled=input.whatsappEnabled; this.fetcher=input.fetcher??fetch; }
  private readonly timeoutMs:number; private readonly whatsappEnabled:boolean; private readonly fetcher:typeof fetch;
  async start(input:{phoneE164:string;channel:MfaChannel}) { if(input.channel==="whatsapp"&&!this.whatsappEnabled) throw new RequiredDependencyUnavailableError("WhatsApp OTP disabled"); const data=await this.request("Verifications",{To:input.phoneE164,Channel:input.channel}); const reported=channel(data.channel); if(typeof data.sid!=="string"||!data.sid||!reported||data.status!=="pending")throw new RequiredDependencyUnavailableError("invalid Twilio verification response"); return {providerChallengeId:data.sid,reportedChannel:reported}; }
  async check(input:{providerChallengeId:string;code:string}):Promise<{approved:boolean;reportedChannel:MfaChannel}> { let response:Response; try {response=await this.fetcher(`${this.base}/VerificationCheck`,{method:"POST",headers:{Authorization:this.authorization,"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({VerificationSid:input.providerChallengeId,Code:input.code}),signal:AbortSignal.timeout(this.timeoutMs)});}catch(e){throw new RequiredDependencyUnavailableError("Twilio unavailable",{cause:e});} if(response.status===404)return{approved:false,reportedChannel:"sms"}; if(!response.ok)throw new RequiredDependencyUnavailableError("Twilio unavailable"); const data=await this.json(response); const reported=channel(data.channel); if(!reported||typeof data.status!=="string")throw new RequiredDependencyUnavailableError("invalid Twilio response"); return {approved:data.status==="approved",reportedChannel:reported}; }
  private async request(path:string,body:Record<string,string>):Promise<TwilioResponse>{let response:Response;try{response=await this.fetcher(`${this.base}/${path}`,{method:"POST",headers:{Authorization:this.authorization,"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(body),signal:AbortSignal.timeout(this.timeoutMs)});}catch(e){throw new RequiredDependencyUnavailableError("Twilio unavailable",{cause:e});}if(!response.ok)throw new RequiredDependencyUnavailableError("Twilio unavailable");return this.json(response);}
  private async json(response:Response):Promise<TwilioResponse>{try{const value:unknown=await response.json();if(!value||typeof value!=="object"||Array.isArray(value))throw new Error();return value as TwilioResponse;}catch(e){throw new RequiredDependencyUnavailableError("invalid Twilio response",{cause:e});}}
}
