import { AuthenticationFailedError, RateLimitedError, RequiredDependencyUnavailableError } from "../../common/errors";
import type { Clock } from "../../common/clock";
import type { SecretGenerator } from "../../common/secret-generator";
import { SECURITY_POLICY } from "../../config/security-policy";
import { hashSecretToken } from "../../crypto/secret-token";
import { maskPhone } from "../../mfa/mfa-challenge";
import type { OtpVerificationGateway } from "../../mfa/otp-verification.gateway";
import type { AuthenticationRepository } from "../../mfa/ports/authentication-repository";
import type { RateLimiter } from "../../rate-limit/rate-limiter";
export class ResendMfaUseCase { constructor(private readonly repo:AuthenticationRepository,private readonly limiter:RateLimiter,private readonly otp:OtpVerificationGateway,private readonly clock:Clock,private readonly secrets:SecretGenerator,private readonly limits:{attempts:number;windowSeconds:number}){} async execute(mfaToken:string){const now=this.clock.now(),prepared=await this.repo.prepareMfaResend(hashSecretToken(mfaToken),now);if(prepared==="invalid")throw new AuthenticationFailedError("invalid mfa attempt");const limited=await this.limiter.hit({scope:"mfa_send_user",subject:prepared.userId,limit:this.limits.attempts,windowSeconds:this.limits.windowSeconds,now});if(!limited.allowed)throw new RateLimitedError(limited.retryAfterSeconds,"mfa resend");let started;try{started=await this.otp.start({phoneE164:prepared.phoneE164,channel:prepared.channel});}catch(error){throw new RequiredDependencyUnavailableError("otp resend",{cause:error});}const mismatch=started.reportedChannel!==prepared.channel,expiresAt=new Date(now.getTime()+SECURITY_POLICY.mfaChallengeTtlSeconds*1000),result=await this.repo.replaceMfaChallenge({attemptId:prepared.attemptId,challenge:{id:this.secrets.randomId(),providerChallengeId:started.providerChallengeId,requestedChannel:prepared.channel,reportedChannel:started.reportedChannel,expiresAt,invalidatedAt:mismatch?now:null},now,auditEvents:[]});if(result!=="replaced")throw new AuthenticationFailedError("invalid mfa attempt");if(mismatch)throw new RequiredDependencyUnavailableError("otp channel mismatch");return {channel:prepared.channel,maskedDestination:maskPhone(prepared.phoneE164),expiresAt};}}
